# k apply -f docs/snippets/tutorials/rfc2136/bind-deployment.yaml
# k delete -f docs/snippets/tutorials/rfc2136/bind-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  namespace: default
  labels:
    app: bind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      containers:
      - name: bind
        image: cytopia/bind
        env:
        - name: DOCKER_LOGS
          value: "1"
        - name: ALLOW_QUERY
          value: any
        ports:
        - containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
spec:
  type: NodePort
  selector:
    app: bind
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 53
      targetPort: 53
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30053
      protocol: UDP
