# ExternalDNS RFC2136 manifest for Kubernetes
# kubectl apply -f docs/snippets/tutorials/rfc2136/extdns-manifest.yaml
# kubectl delete -f docs/snippets/tutorials/rfc2136/extdns-manifest.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: rfc2136-tsig
  namespace: default
type: Opaque
stringData:
  tsig: "2Jw1r0k9zC3cG1t7Gqv1b7g0k9zC3cG1t7Gqv1b7g0k="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
  labels:
    app: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.19.0
          args:
            - --interval=10s
            - --source=service
            - --domain-filter=example.org
            - --provider=rfc2136
            - --rfc2136-host=bind9.default.svc.cluster.local
            - --rfc2136-host=10.244.1.127
            - --rfc2136-port=53
            - --rfc2136-zone=example.org.
            # - --rfc2136-tsig-keyname=tsig-key.
            # - --rfc2136-tsig-secret="2Jw1r0k9zC3cG1t7Gqv1b7g0k9zC3cG1t7Gqv1b7g0k="
            # - --rfc2136-tsig-secret-alg=hmac-sha256
            - --rfc2136-insecure
            - --registry=txt
            - --txt-owner-id=kind-cluster
            - --log-level=debug
            - --txt-prefix=extdns-
          env:
            - name: TSIG
              valueFrom:
                secretKeyRef:
                  name: rfc2136-tsig
                  key: tsig
