name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:

  build:
    permissions:
      contents: read  #  to fetch code (actions/checkout)
      checks: write  #  to create a new check based on the results (shogo82148/actions-goveralls)
      issues: write

    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
      id: go

    - name: Install CI
      run: |
        go get -v -t -d ./...

    - name: Test
      run: make test

    - name: Coveralls
      # https://github.com/marketplace/actions/coveralls-github-action
      uses: coverallsapp/github-action@v2
      with:
        file: profile.cov
        format: golang
        # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
        github-token: ${{ secrets.GITHUB_TOKEN }}
